services:
  aigod-fusion-image:
    build:
      context: .
      dockerfile: Dockerfile
    image: aigod-fusion-image:latest
    container_name: aigod-fusion-image
    restart: unless-stopped
    ports:
      - "5487:80"
